### ISSUE TITLE
Forked it, want to publish it

### ISSUE THREAD

**Issue by ChessSpider** [tcoenraad/python-dvsportal#3]
Hi @tcoenraad , I used the code of this repository as a base to create a home assistant custom  component: https://github.com/ChessSpider/dvsportal 

Ive made some minor changes to it, but the base is still your original code

If I want to officially publish my home assistant componen, i need to move all API specific logic to a pypi published package (https://developers.home-assistant.io/docs/creating_component_code_review#4-communication-with-devicesservices)

I wanted to check in with you if that's OK with you and if you have any preferences how i named said package.. I noticed you havent claimed dvsportal yet on pypi.

**Comment by tcoenraad** [comment]
Go ahead! I once published some alphas of this repo, but removed them when I moved and was no longer able to test dvsportal myself.

**Comment by ChessSpider** [comment]
thank you! when ill have time ill continue working on it!
